name: 'Build & Test'

on:
  push:
    branches: ["main"]

jobs:
  buid:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 'Setup Java 21'
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: 'Change wrapper permissions'
        run: chmod +x ./gradlew
      - name: 'Build with Gradle'
        run: ./gradlew build
      - name: 'Build finished.'
        run: echo 'Build finished successfully.'